name: Publish

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Publish
        run: npx vsce publish -p ${{ secrets.PERSONAL_ACCESS_TOKEN }}
